name: 🐛 Bug Report
description: Report a bug or issue with AIToolbox.software
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🔥🔥 Community highlight: Earn Level 3 by sharing AIToolbox on your social media.
        Learn more: https://github.com/huamanraj/aitoolbox.software/blob/main/contributions/Community.md

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: Describe the bug...
  - type: textarea
    id: repro_or_recording
    attributes:
      label: Steps or Recording
      description: Steps to reproduce or a link to a screen recording.
      placeholder: |
        1. ...
        2. ...
        3. ...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Paste screenshots/images if helpful.
