name: 📚 Documentation
description: Report documentation issues or suggest improvements
title: "[DOCS] "
labels: ["documentation"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What’s wrong or what should be improved?
      placeholder: Describe the documentation issue or suggestion...
  - type: textarea
    id: screenshots_or_recording
    attributes:
      label: Screenshots or Recording
      description: Add screenshots or a link to a recording if helpful.