name: ✨ Feature Request
description: Suggest a new feature for AIToolbox.software
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Available Features
        **⚠️ Only features from this list can be implemented:** [**View Available Features**](https://drive.google.com/file/d/1QWFg2C5ih-XH3i_xRZBi_EVnaMLpzkh1/view?usp=sharing)

  - type: markdown
    attributes:
      value: |
        🔥🔥 Community highlight: Earn Level 3 by sharing AIToolbox on your social media.
        Learn more: https://github.com/huamanraj/aitoolbox.software/blob/main/contributions/Community.md

  - type: textarea
    id: feature-description
    attributes:
      label: ✨ Feature Description
      description: Which feature from the available list would you like to see added?
      placeholder: Describe the feature you want from the available options...
