name: 🚀 Improvement
description: Suggest an improvement to existing functionality in AIToolbox.software
title: "[IMPROVEMENT] "
labels: ["improvement", "enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📋 Before moving ahead
        - ⭐ Please star the repository (Mandatory for GSSoC 25).
        - 📖 Read the [Contribution Guidelines](https://github.com/AIToolbox-software/AIToolbox.software/blob/main/contribution/CONTRIBUTING.md).
        - 📂 All contribution info is inside the [`/contribution`](https://github.com/AIToolbox-software/AIToolbox.software/tree/main/contribution) folder.
        - 📚 AI and AdSense related documentation is inside the [`/doc`](https://github.com/AIToolbox-software/AIToolbox.software/tree/main/doc) folder.



  - type: textarea
    id: proposed-improvement
    attributes:
      label: ✨ Proposed Improvement
      description: Describe the improvement you'd like to see.
      placeholder: How should it work better?
    validations:
      required: true


  - type: textarea
    id: benefits
    attributes:
      label: 🎁 Expected Benefits
      description: What benefits would this improvement provide?
      placeholder: |
        - Benefit 1: ...
        - Benefit 2: ...
        - Benefit 3: ...
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 💡 Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: Any technical suggestions or approaches?


