name: 🗒️ Other
description: Open a blank issue
title: "[OTHER] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to open a blank, free-form issue.
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Share any context, links, or notes.
      placeholder: Type anything here...
    validations:
      required: false
