name: ❓ Question/Support
description: Ask a question or request support
title: "[QUESTION] "
labels: ["question", "support"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🔥🔥 Community highlight: Earn Level 3 by sharing AIToolbox on your social media.
        Learn more: https://github.com/huamanraj/aitoolbox.software/blob/main/contributions/Community.md

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you need help with?
      placeholder: Ask your question or describe your issue...
  - type: textarea
    id: screenshots_or_recording
    attributes:
      label: Screenshots or Recording
      description: Add screenshots or a link to a recording if helpful.
