name: Auto reply on new issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add auto-reply comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🔥🔥 Community highlight: Earn Level 3 by sharing AIToolbox on your social media.
            ⚠️Learn more: https://github.com/huamanraj/aitoolbox.software/blob/main/contributions/Community.md

            Before moving ahead:
            - ⭐ Please star the repository (Mandatory for GSSoC 25).
            - 📖 Read the [Contribution Guidelines](https://github.com/${{ github.repository }}/blob/main/contribution/CONTRIBUTING.md).
            - 📂 All contribution info is inside the [`/contribution`](https://github.com/${{ github.repository }}/tree/main/contribution) folder.
            - 📚 AI and AdSense related documentation is inside the [`/doc`](https://github.com/${{ github.repository }}/tree/main/doc) folder.

            We’ll review your issue soon.
